apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: mindlyf

patches:
  - path: patches/replicas.yaml

configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info

images:
  - name: ${ECR_REGISTRY}/api-gateway
    newName: ${ECR_REGISTRY}/api-gateway
    newTag: latest
  - name: ${ECR_REGISTRY}/auth-service
    newName: ${ECR_REGISTRY}/auth-service
    newTag: latest
  - name: ${ECR_REGISTRY}/ai-service
    newName: ${ECR_REGISTRY}/ai-service
    newTag: latest
  - name: ${ECR_REGISTRY}/journal-service
    newName: ${ECR_REGISTRY}/journal-service
    newTag: latest
  - name: ${ECR_REGISTRY}/recommender-service
    newName: ${ECR_REGISTRY}/recommender-service
    newTag: latest
  - name: ${ECR_REGISTRY}/chat-service
    newName: ${ECR_REGISTRY}/chat-service
    newTag: latest
  - name: ${ECR_REGISTRY}/reporting-service
    newName: ${ECR_REGISTRY}/reporting-service
    newTag: latest
  - name: ${ECR_REGISTRY}/teletherapy-service
    newName: ${ECR_REGISTRY}/teletherapy-service
    newTag: latest 