apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: mindlyf
  labels:
    app: ai-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service
        image: ${ECR_REGISTRY}/ai-service:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: OPENAI_API_KEY
        - name: PORT
          value: "8000"
        - name: MODEL_VERSION
          value: "gpt-4"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: mindlyf
spec:
  selector:
    app: ai-service
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP 