apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: mindlyfe
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ${ECR_REGISTRY}/auth-service:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: NODE_ENV
        - name: PORT
          value: "3001"
        - name: AWS_COGNITO_USER_POOL_ID
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: AWS_COGNITO_USER_POOL_ID
        - name: AWS_COGNITO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: AWS_COGNITO_CLIENT_ID
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: mindlyfe
spec:
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 3001
  type: ClusterIP