apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: mindlyfe
  labels:
    app: chat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: ${ECR_REGISTRY}/chat-service:latest
        ports:
        - containerPort: 3002
        - containerPort: 3003
          name: websocket
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: NODE_ENV
        - name: PORT
          value: "3002"
        - name: WS_PORT
          value: "3003"
        - name: REDIS_HOST
          value: "${REDIS_HOST}"
        - name: REDIS_PORT
          value: "${REDIS_PORT}"
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: AUTH_SERVICE_URL
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: mindlyfe
spec:
  selector:
    app: chat-service
  ports:
  - port: 80
    targetPort: 3002
    name: http
  - port: 3003
    targetPort: 3003
    name: websocket
  type: ClusterIP