apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
  namespace: mindlyf
  labels:
    app: reporting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: ${ECR_REGISTRY}/reporting-service:latest
        ports:
        - containerPort: 3004
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: NODE_ENV
        - name: PORT
          value: "3004"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_PASSWORD
        - name: AWS_REGION
          value: "${AWS_REGION}"
        - name: ATHENA_DATABASE
          value: "mindlyf_analytics"
        - name: ATHENA_WORKGROUP
          value: "mindlyf-${ENVIRONMENT}"
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 20
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: mindlyf
spec:
  selector:
    app: reporting-service
  ports:
  - port: 80
    targetPort: 3004
  type: ClusterIP 