version: '3.8'

services:
  # Auth Service with SQLite (no external database needed)
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindlyf-auth-service-local
    environment:
      NODE_ENV: development
      PORT: 3001
      
      # Database Configuration (SQLite)
      DATABASE_TYPE: sqlite
      DATABASE_DATABASE: ./mindlyf_auth.sqlite
      DATABASE_SYNCHRONIZE: true
      DATABASE_LOGGING: true
      
      # JWT Configuration
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      JWT_REFRESH_EXPIRES_IN: 7d
      
      # Service Configuration
      SERVICE_NAME: auth-service
      SERVICE_VERSION: 1.0.0
      
      # Rate Limiting
      THROTTLE_TTL: 60
      THROTTLE_LIMIT: 100
      
      # Payment Configuration (Mock for testing)
      PAYMENT_PROVIDER_API_KEY: test-api-key
      PAYMENT_WEBHOOK_SECRET: test-webhook-secret
      
      # Feature Flags
      ENABLE_ORGANIZATION_PLANS: true
      ENABLE_CREDIT_SYSTEM: true
      ENABLE_AUTO_RENEWAL: true
      
      # Security
      BCRYPT_ROUNDS: 10
      
    ports:
      - "3001:3001"
    volumes:
      - ./mindlyf_auth.sqlite:/app/mindlyf_auth.sqlite
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health/ping"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

networks:
  default:
    name: mindlyf-local-network 