version: '3.8'

services:
  notification-service:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "3005:3005"
    env_file:
      - .env
    environment:
      - DB_HOST=notification-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mindlyf_notification
      - DB_SYNC=true
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      - notification-db
    networks:
      - mindlyf-network

  notification-db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mindlyf_notification
    ports:
      - "5435:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    networks:
      - mindlyf-network

volumes:
  notification-db-data:

networks:
  mindlyf-network:
    external: true 