apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      kubernetes_url https://kubernetes.default.svc
      bearer_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
      ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      skip_labels false
      skip_container_metadata false
      skip_namespace_metadata false
      skip_master_url false
    </filter>

    <filter kubernetes.var.log.containers.**>
      @type record_transformer
      enable_ruby
      <record>
        service_name ${record.dig("kubernetes", "labels", "app") || record.dig("kubernetes", "container_name")}
        namespace ${record.dig("kubernetes", "namespace_name")}
        pod_name ${record.dig("kubernetes", "pod_name")}
        container_name ${record.dig("kubernetes", "container_name")}
      </record>
    </filter>

    # Add log level field based on text pattern
    <filter kubernetes.var.log.containers.**>
      @type grep
      <regexp>
        key log
        pattern /\b(ERROR|error|Error)\b/
      </regexp>
      <add>
        field log_level
        value error
      </add>
    </filter>

    <filter kubernetes.var.log.containers.**>
      @type grep
      <regexp>
        key log
        pattern /\b(WARN|warn|Warning)\b/
      </regexp>
      <exclude>
        key log
        pattern /\b(ERROR|error|Error)\b/
      </exclude>
      <add>
        field log_level
        value warning
      </add>
    </filter>

    <filter kubernetes.var.log.containers.**>
      @type grep
      <regexp>
        key log
        pattern /\b(INFO|info|Information)\b/
      </regexp>
      <exclude>
        key log
        pattern /\b(ERROR|error|Error|WARN|warn|Warning)\b/
      </exclude>
      <add>
        field log_level
        value info
      </add>
    </filter>

    <match kubernetes.var.log.containers.**>
      @type elasticsearch
      host elasticsearch
      port 9200
      logstash_format true
      logstash_prefix mindlyf-logs
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match> 